In [ ]:
# Cell 1: Install & import libraries
!pip install requests beautifulsoup4 pandas lxml tabula-py pdfminer.six tqdm

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re, io, json, time
from tqdm import tqdm

In [2]:
# Cell 2: Define the comprehensive sources from your original app
sources = {
    'nfhs5_data': {
        'https://doi.org/10.1186/s12889-024-18784-4': 'NFHS-5 Data (Headcount/Table 2 - BMC Public Health)',
        'https://doi.org/10.1371/journal.pone.0305205': 'NFHS-5 Data (Spatial Clustering/Hotspots - PLoS ONE)',
    },
    'treatment_patterns': {
        'https://www.grandviewresearch.com/industry-analysis/india-glp-1-receptor-agonist-market-report': 'GLP-1 Market Growth Rate (CAGR 2025-2030)',
        'https://m.economictimes.com/industry/healthcare/biotech/pharmaceuticals/a-big-fat-fight-has-just-broken-out-in-india/articleshow/122049705.cms': 'GLP-1 Anti-Obesity Drug Market Value (March 2025) & Pricing',
        'https://www.iosrjournals.org/iosr-jpbs/papers/Vol19-issue6/Ser-2/L1906027179.pdf': 'GLP-1 Patient Openness/Barriers (77.3% Openness)',
        'https://nobesity.in/weight-loss-surgery-cost-in-india/': 'Bariatric Surgery Cost Range (Lakhs)',
        'https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2024.1382814/full': 'Lifestyle Intervention (Clinical Basis)',
    }
}

In [3]:
# Cell 3: Extract NFHS-5 tables dynamically
nfhs_tables = []

for url, desc in sources['nfhs5_data'].items():
    print(f"\n🔗 {desc}\n{url}")
    try:
        res = requests.get(url, timeout=20)
        res.raise_for_status()
        tables = pd.read_html(res.text)
        print(f"✅ Found {len(tables)} tables")

        for t in tables:
            if any(re.search(r'obese|bmi|overweight', str(c), re.I) for c in t.columns):
                nfhs_tables.append({'source': url, 'table': t})
                display(t.head())
    except Exception as e:
        print(f"❌ Error parsing {url}: {e}")

🔗 NFHS-5 Data (Headcount/Table 2 - BMC Public Health)
https://doi.org/10.1186/s12889-024-18784-4

C:\Users\HP\AppData\Local\Temp\ipykernel_11888\3143599539.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(res.text)

❌ Error parsing https://doi.org/10.1186/s12889-024-18784-4: Missing optional dependency 'html5lib'.  Use pip or conda to install html5lib.

🔗 NFHS-5 Data (Spatial Clustering/Hotspots - PLoS ONE)
https://doi.org/10.1371/journal.pone.0305205
❌ Error parsing https://doi.org/10.1371/journal.pone.0305205: Missing optional dependency 'html5lib'.  Use pip or conda to install html5lib.

In [12]:
# couldnt get the tavle extracted from url so we donwloaded the pdf and continued the process
import camelot
import pandas as pd

pdf_path = r"C:\Users\HP\Desktop\wegovy\prevelance.pdf"

# Try stream mode (better for tables without lines)
tables = camelot.read_pdf(pdf_path, pages='all', flavor='stream')

print(f"✅ Extracted {len(tables)} tables using stream mode")

for i, t in enumerate(tables):
    print(f"\n--- Table {i+1} ---")
    print(t.df.head(10))  # show first few rows

D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (53.12209632999997, 234.6434021, 544.1420963300002, 575.308619744009)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (170.544998168, 42.33909985299998, 548.7986981706749, 168.78634801500897)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692901610999996, 149.006393432, 540.9257016308322, 268.4828936668485)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692897883000015, 154.870803833, 543.541697876896, 267.67200378525)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

✅ Extracted 18 tables using stream mode

--- Table 1 ---
                                                   0
0                              S. V. Subramanian1,6*
1                                           Abstract
2  Background  The problem of overweight/obesity ...
3  and middle-income countries. BMI change in Ind...
4  Methods  This repeated cross-sectional study o...
5  categories of BMI among adults (age 20–54) in ...
6  2015–2016, and 2019–2021) for 36 states/UTs. S...
7  The categories were Severely/Moderately Thin (...
8  (25.0-29.9), and Obese (≥ 30.0). We also estim...
9  and headcount burden to quantify the trend of ...

--- Table 2 ---
                                                   0
0  © The Author(s) 2024. Open Access This article...
1  permits use, sharing, adaptation, distribution...
2  original author(s) and the source, provide a l...
3  other third party material in this article are...
4  to the material. If material is not included i...
5  regulation or exceeds the permitted use, you w...
6  licence, visit http://creativecommons.org/lice...
7  mons.org/publicdomain/zero/1.0/) applies to th...

--- Table 3 ---
                                                   0  \
0                                         Background
1
2  The Sustainable Development Goal (SDG) 2 seeks...
3  hunger  and  ensure  access  to  safe,  nutrit...
4  cient food year-round by 2030. The SDG 3 aims ...
5  healthy lives and promote wellbeing for all at...
6  It is important to evaluate the nutritional st...
7  effective  policies  to  ascertain  these  goa...
8  Index (BMI) serves as a good metric for evalua...
9  ulation-level  nutritional  status  and  futur...

                                                   1
0
1  (NFHS-5)  or  did  not  analyze  the  change  ...
2  over 20 years using a representative public da...
3  is  also  a  dearth  of  literature  focusing ...
4  difference in BMI outcomes. (Additional file 1...
5                                               S1).
6  In  this  study,  we  present  an  up-to-date ...
7  hensive description of the trends in the preva...
8  ferent  BMI  categories  among  adults  in  In...
9  states/UTs  between  1999  and  2021.  We  use...

--- Table 4 ---
                                                   0  \
0  Recode dataset for men as BMI data was not pre...
1             the individual interview data for men.
2
3                                   Study population
4
5  The study population was adult women aged 20–4...
6  who were not currently pregnant and had not gi...
7  in  the  last  two  months,  and  men  aged  2...
8  lived in households that were selected for the...
9  ule.  Men’s  data  was  not  collected  in  th...

                                                   1
0  time whereas a positive SAC value indicates ri...
1                          lence during this period.
2  We used box plots and heat tables to assess th...
3
4  to  which \nstate \ninequalities \nin  BMI  ou...
5  increased/decreased  over  time.  Descriptive ...
6  of  the  state-level  patterns  over  time  we...
7  scatterplots  and  correlations.  Specifically...
8  whether  the  magnitude  and  patterns  of  ch...
9  related  with  the  prevalence  of  BMI  outco...

--- Table 5 ---
                     0                                                  1  \
0                       Table 1  Study sample size selection from the ...
1  Survey round (Year)
2                                                            criteria (n)
3                                                                   Women
4      NFHS-2(1998-99)                                             76,880
5      NFHS-3(2005-06)                                             94,575
6      NFHS-4(2015-16)                                            540,840
7      NFHS-5(2019-21)                                            569,203
8            All waves                                          1,281,498

                                2             3  \
0
1  Sample size based on inclusion
2
3                             Men         Women
4                               -   5,495 (7.1)
5                          74,572   4,242 (4.5)
6                         105,351   9,407 (1.7)
7                          95,726  18,176 (3.2)
8                         270,814  37,320 (2.9)

                                         4                        5        6
0
1  Missing or implausible values (n , (%))  Final study sample size
2
3                                      Men                    Women      Men
4                                        -                   71,385        -
5                            15,637 (26.5)                   90,333   58,935
6                            12,777 (13.8)                  531,433   92,574
7                            13,528 (16.5)                  551,027   82,198
8                            37,107 (13.7)                1,244,178  233,707

--- Table 6 ---
                                                   0
0  Fig. 1  Comparative Distribution of Body Mass ...
1  both panels (A) and (B), the upper bar represe...
2  for the latest period (2021). The cutoff point...
3  Overweight (25.0-29.9), and Obese ( ≥30.0) A W...
4  Nicobar, Chandigarh, Dadra and Nagar Haveli an...
5  B Men. The earliest survey period for Andaman ...
6  earliest survey period for all other states is...

--- Table 7 ---
                                                   0  \
0  earliest survey period for all other states is...
1  (absolute  change:  women + 1.2%;  men + 1.2%)...
2                                    Figs. 1 and 2).
3  Rural areas consistently show a higher rate of...
4  compared to urban areas, which exhibit greater...
5  of overweight and obesity. For instance, the r...

                                                   1
0
1  or  moderate  thinness  in  urban  India  in  ...
2  for  women  and  2.5%  for  men,  whereas  in ...
3  these  figures  rose  to  6.2%  and  3.5%,  re...
4  versely, obesity rates were higher in urban se...
5  11.0% of women and 6.6% of men being affected ...

--- Table 8 ---
                                                   0             1
0  Sung et al. BMC Public Health         (2024) 2...  Page 5 of 12
1  Fig. 2  Summary distribution of state/Union Te...
2  shows the variability of a data set using lowe...
3  and maximum values, respectively. The upper ou...
4  within the box (separating the darker and ligh...

--- Table 9 ---
            0                                   1               2  \
0  divided by
1   Height^2)
2              Severely /Moderately Thin (< 17.0)
3         All                                       9,647 (13.5%)
4       Urban                                        1,958 (8.4%)
5       Rural                                       7,689 (16.0%)
6                         Mildly Thin (17.0-18.4)
7         All                                      12,963 (18.2%)
8       Urban                                       2,736 (11.7%)
9       Rural                                      10,227 (21.3%)

                3               4              5              6  \
0
1
2
3  10,384 (11.5%)   38,536 (7.3%)  30,424 (5.5%)   4,909 (8.3%)
4    3,296 (8.0%)    7,165 (4.5%)   4,906 (3.5%)   1,967 (6.7%)
5   7,088 (14.5%)   31,371 (8.4%)  25,518 (6.2%)  2,942 (10.0%)
6
7  13,683 (15.1%)  60,255 (11.3%)  47,791 (8.7%)  8,925 (15.1%)
8   4,327 (10.5%)   11,300 (7.1%)   7,554 (5.4%)  3,397 (11.5%)
9   9,356 (19.1%)  48,955 (13.1%)  40,237 (9.8%)  5,528 (18.7%)

               7             8
0
1
2
3   4,296 (4.6%)  2,645 (3.2%)
4   1,070 (3.7%)    517 (2.5%)
5   3,226 (5.1%)  2,128 (3.5%)
6
7   9,094 (9.8%)  5,611 (6.8%)
8   1,934 (6.7%)    955 (4.5%)
9  7,160 (11.3%)  4,656 (7.6%)

--- Table 10 ---
                                                   0  \
0       Rural\n568 (1.2%)\n887 (1.8%)\n12,530 (3.4%)
1  compared  to  4.8%  of  women  and  3.3%  of  ...
2  locations.  The  patterns  of  BMI  change \nf...
3  urban populations followed the overall trend o...
4  ing thinness and increasing overweight/obesity...
5                             Figure S1, Figure S2).
6  More than half of the population consistently ...
7  sified as “Normal” BMI, ranging from 55 to 65%...
8
9  Changes in the geographic distribution of BMI ...

                                                   1
0  19,718 (4.8%)\n246 (0.8%)\n1,391 (2.2%)\n2,031...
1  Madhya  Pradesh, \nand  Tripura) \nshowed \nan...
2  between  1999  and  2006.  Obesity  substantia...
3  in Tamil Nadu (SAC 1999–2021: 0.58%), Andhra P...
4  (0.49%),  and  Haryana  (0.34%)  (Fig.  3,  Fi...
5  S4 shows the detailed SAC between each survey ...
6  Trends  for  men  were  similar  to  those  in...
7  the  prevalence  of  extreme  categories  (sev...
8  ately  thin  and  obese)  was  less  than  for...
9

--- Table 11 ---
                                                   0
0  Fig. 3  Standardized Absolute Change (SAC, per...
1  across States/Union Territories. A Women, SAC ...
2  and Nagar Haveli and Daman and Diu, Lakshadwee...
3  in the NFHS survey in 1999. B Men, SAC from 20...
4  and Daman and Diu, Lakshadweep, and Puducherry...
5                                            in 2006

--- Table 12 ---
                                                   0  \
0  and Daman and Diu, Lakshadweep, and Puducherry...
1                                            in 2006
2
3  between the rankings across years. A correlati...
4  1  indicates  the  ranking  of  states  has  n...
5  over  time  and  a  smaller  value  suggests  ...
6  ranking  (Table  S2).  The  rank  correlation ...
7  ordering of states/UTs was strong (> 0.7) for ...
8          except normal BMI for both women and men.

                                                   1
0
1
2       Estimated headcount of BMI outcomes in India
3
4  In 2021, approximately 29,412,236 adults were ...
5  moderately thin in India (Fig. 4). The populat...
6  count  varied  from  4,230,340  in  Maharashtr...
7  Ladakh. Maharashtra (13.94%), Gujarat (10.82%)...
8

--- Table 13 ---
                                                   0  \
0  separately and summed up to estimate values fo...
1            shades representing a larger proportion
2  (10.72%) and Uttar Pradesh (9.91%) account for...
3  of the total burden of severely/moderately thi...
4  In  2021,  approximately  37,599,029  adults  ...
5  in \nIndia \n(Fig.  4).  The  population  head...
6  from  4,676,538 \nin  Maharashtra  to  2,815 \...
7  weep.  Maharashtra  (12.05%),  Tamil  Nadu  (9...
8  Pradesh \n(9.60%),  and  Karnataka \n(9.00%)  ...
9    40.48% of the total burden of obesity in India.

                                                   1
0
1
2  States/UTs  with  a  higher  prevalence  of  t...
3  average,  tend  to  have  a  larger  absolute ...
4  men \nand  women \n(severely/moderately \nthin...
5  r = 0.59,  men  r = 0.60;  mildly  thin:  wome...
6  r = 0.55) (Fig. 5). Distributions of states fo...
7  erately thin and mildly thin resemble each oth...
8  Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, ...
9  Karnataka,  Madhya \nPradesh,  Maharashtra,  O...

--- Table 14 ---
                                                   0  \
0  Telangana,  Uttar  Pradesh,  and  West  Bengal...
1  with  High  Prevalence  and  High  Burden \n(h...
2  (Type  IV)  for  both  severely/moderately  th...
3  thin in case of both men and women. Himachal P...
4  and Tripura have Low Prevalence and Low Burden...
5                                                I).
6  On the other hand, the relationship between he...
7  burden and prevalence of overweight and obese ...
8  clear  as  thin  populations.  The  distributi...
9  overweight  and  obesity  for  both  genders. ...

                                                   1
0  of  reproductive  age,  our  study  offers  in...
1  prevalence  of  both  underweight  and  overwe...
2  sity  conditions  across  Indian  states  for ...
3                                             women.
4  There  were  several  limitations  of  the  st...
5  absence of data on men in the NFHS-2 survey (1...
6  complicates  the  gender  comparison  over  th...
7  ond, the NFHS-5, initiated in 2019, encountere...
8  tions  due  to  the  COVID-19  pandemic,  whic...
9  the  continuity  and  comprehensiveness  of  t...

--- Table 15 ---
                                                   0              1
0  Sung et al. BMC Public Health         (2024) 2...  Page 10 of 12
1            Fig. 5 \n(See legend on previous page.)

--- Table 16 ---
                                                   0  \
0
1  education;  and  healthcare  strengthening  fo...
2
3  universal coverage of essential nutrition acti...
4  Additionally,  gender  differences  in  BMI  a...
5  The gender differences in overweight/obesity i...
6  be attributed to health risk factors, such as ...
7  cal activity among women respondents [38]. Pos...
8
9  weight  retention  could  also  cause  higher ...

                                                   1
0                    WHO \nWorld health organization
1
2                 SAC \nStandardized absolute change
3     IPUMS \nIntegrated public use microdata series
4                EAG \nEmpowered action group states
5
6                          Supplementary Information
7  The online version contains supplementary mate...
8               org/ 10. 1186/ s12889- 024- 18784-4.
9

--- Table 17 ---
                                                   0  \
0  and  develop  new  interventions  to  target  ...
1                                      malnutrition.
2                                      Abbreviations
3                              BMI \nBody mass index
4               NFHS \nNational family health survey
5                             UT \nUnion territories
6                 SDG \nSustainable development goal
7           LMIC \nLow- and middle- income countries
8                DBM \nDouble burden of malnutrition

                                                   1
0
1
2                                         References
3  1.  \nUNDP. The SDGs In Action: United nations...
4  2022.https:// www. undp. org/ africa/ waca/ sd...
5                                              2024.
6
7
8

--- Table 18 ---
                                                   0  \
0  2.  \nCDC. Body Mass Index: Considerations for...
1  ease control and prevention. 2021. https:// ww...
2  oads/ bmifo rpact ition ers. pdf. Accessed 13 ...
3  3.   WHO. The double burden of malnutrition: p...
4  Organization; 2016. https:// www. who. int/ pu...
5               NMH- NHD- 17.3. Accessed 13 May 2024
6  4.   Wells JC, Sawaya AL, Wibaek R, et al. The...
7  tion: aetiological pathways and consequences f...
8                             2020;395(10217):75–88.
9  5.  \nPopkin BM, Corvalan C, Grummer-Strawn LM...

                                                   1
0  24.  \nInternational Institute for Population ...
1  Family Health Survey (NFHS-2), 1998–99: India....
2  dhspr ogram. com/ pubs/ pdf/ frind2/ frind2. p...
3  25.  \nInternational Institute for Population ...
4  Family Health Survey (NFHS-3), 2005–06: India....
5  dhspr ogram. com/ pubs/ pdf/ frind3/ frind3- v...
6                                          May 2024.
7  26.  \nInternational Institute for Population ...
8  Family Health Survey (NFHS-4), 2015-16: India....
9  ogram. com/ pubs/ pdf/ fr339/ fr339. pdf. Acce...

In [13]:
def extract_tables_smart(pdf_path):
    """
    Extract tables from a PDF using both lattice and stream,
    then pick the one with the most non-empty content.
    """
    import camelot, os, pandas as pd

    if not os.path.exists(pdf_path):
        print(f"❌ File not found: {pdf_path}")
        return []
    
    results = []
    for flavor in ["lattice", "stream"]:
        try:
            print(f"🔍 Trying {flavor} mode...")
            tables = camelot.read_pdf(pdf_path, pages="all", flavor=flavor)
            dfs = [t.df for t in tables if not t.df.empty]
            print(f"✅ {len(dfs)} non-empty tables found using {flavor}")
            results.extend(dfs)
        except Exception as e:
            print(f"⚠️ {flavor} failed: {e}")

    # remove duplicates by shape/content
    unique_tables = []
    seen = set()
    for df in results:
        key = (df.shape, df.head().to_string())
        if key not in seen:
            unique_tables.append(df)
            seen.add(key)

    print(f"📊 {len(unique_tables)} unique tables extracted.")
    return unique_tables

In [15]:
import pdfplumber
import pytesseract
from PIL import Image
import pandas as pd

pdf_path = r"C:\Users\HP\Desktop\wegovy\prevelance.pdf"

tables_data = []
with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages):
        print(f"🧾 OCR scanning page {i+1}...")
        im = page.to_image(resolution=300)
        text = pytesseract.image_to_string(im.original)
        print(text[:500])  # preview extracted text

🧾 OCR scanning page 1...
Sung et al. BMC PublicHealth (2024) 24:1322 BMC Public Health
https://doi.org/10.1186/s12889-024-18784-4

, ®
Temporal change in prevalence of BMI cz

categories in India: patterns across States
and Union territories of India, 1999-2021

Meekang Sung'®, Akhil Kumar?®, Raman Mishra’®, Bharati Kulkarni*®, Rockli Kim?°® and
S.V. Subramanian!*"®

Abstract

Background The problem of overweight/obesity often coexists with the burden of undernutrition in most low-
and middle-income countries. BMI chang
🧾 OCR scanning page 2...
Sung et al. BMC Public Health (2024) 24:1322

Background

The Sustainable Development Goal (SDG) 2 seeks to end
hunger and ensure access to safe, nutritious, and suffi-
cient food year-round by 2030. The SDG 3 aims to ensure
healthy lives and promote wellbeing for all at all ages [1].
It is important to evaluate the nutritional status to devise
effective policies to ascertain these goals. Body Mass
Index (BMI) serves as a good metric for evaluating pop-
ulation-level nutritional status and futur
🧾 OCR scanning page 3...
Sung et al. BMC Public Health (2024) 24:1322

Recode dataset for men as BMI data was not present in
the individual interview data for men.

Study population

The study population was adult women aged 20-49 years
who were not currently pregnant and had not given birth
in the last two months, and men aged 20-54 years who
lived in households that were selected for the state mod-
ule. Men’s data was not collected in the 1998-99 round,
limiting the study population to only women in 1998-99.
The upper
🧾 OCR scanning page 4...
Sung et al. BMC PublicHealth (2024) 24:1322 Page 4 of 12

Table 1 Study sample size selection from the four National Family Health Surveys (NFHS), 1999-2021

Survey round (Year) Sample size based on inclusion Missing or implausible values (n , (%)) Final study sample size
criteria (n)

Women Men Women Men Women Men
NFHS-2(1 998-99) 76,880 - 5A95 (7.1) - 71,385 -
NFHS- pore im 94,575 74,572 4,242 (4.5) 15,637 (26.5) 90,333 58,935
NFHS-4(201 5-16) 540,840 105,351 9,A07 (1.7) 12,777 (13.8) 531,433
🧾 OCR scanning page 5...
Sung et al. BMC PublicHealth (2024) 24:1322 Page 5 of 12

A. Women, 1999-2021

85 4
80 4
75 4
70 4
65 4
60 4
55
504]
454

40 >

Prevalence(%)

35 4

26 .

20 T

1999 2006 2016 2021 1999 2006 2016 2021 1999 2006 2016 2021 1999 2006 2016 2021 1999 2006 2016 2021

Severely/Moderately Thin Mildly Thin Normal Overweight Obese

B. Men, 2006-2021

85
80 4
75
70 4
65
604
554
50 |
454

40 4 —

Prevalence(%)

35 4

30 4

25 |

204

57 tL .
1
of -— + ft en sa 7 +
2006 2016 2021 2006 2016 2021 2006 2016 202
🧾 OCR scanning page 6...
Sung et al. BMC Public Health (2024) 24:1322

Page 6 of 12

Table 2 Sample size (n) and prevalence (%) of Body Mass Index (BMI) categories by year

Men

Women
BMI 1999 (n=71,385) 2006 (n=90,333) 2016 (n=531,433)
Category (Weight
divided by
Height42)

2021 (9 =551,027) 2006 (n=58,935) 2016 (n=92,574) 2021 (n= 82,198)

Severely /Moderately Thin (< 17.0)

All 9,647 (13.5%) 10,384 (11.5%) 38,536 (7.3%)
Urban 958 (8.4%) 3,296 (8.0%) 7,165 (4.5%)
ural 7,689 (16.0%) 7,088 (14.5%) 31,371 (8.4%)
Mildly T
🧾 OCR scanning page 7...
Sung et al. BMC Public Health (2024) 24:1322 Page 7 of 12
A. Women, SAC from 1999 to 2021
2075160151) -0.5010-0.26 = -0.25 to -0.01 0.00 to 0.25 0.26 to 0.50 0.76 to 1.00 >1,00
Severely/Moderately Mildly Thin Normal Overweight Obese
All Urban Rural All Urban Rural All Urban Rural All Urban Rural All Urban Rural
Total -0.47 0.27 -0.53 -0.51 -0.31 -0.57 0.23 0.00 0.34 . 0.33 : 0.23 0.26 0.20
Andhra Pradesh | -0.56 -0.32 -0.62 -0.57 -0.27 -0.65 “0.11 -0.66 0.09 0.40
Arunachal Pradesh —-0.09 -0.04 -
🧾 OCR scanning page 8...
Sung et al. BMC Public Health (2024) 24:1322

Page 8 of 12

<1%

Severely/
Moderately Mildly Thin Normal Overweight Obese
Thin
India 29,412,236 50,021,199 389,110,427 137,188,470 37,599,029

Andhra Pradesh
Arunachal Pradesh

18,097,616
263,095

98,250 16,753

Assam 16,196,011
Bihar 36,084,214
Chhattisgarh 7,441,590
Goa 712,838
Gujarat 26,230,139
Haryana 4,676,904
Himachal Pradesh 2,556,529
Jharkhand 7,441,640
Karnataka 25,709,842
Kerala 10,700,571
Madhya Pradesh 16,185,098
Maharashtra
Manipur 94
🧾 OCR scanning page 9...
Sung et al. BMC Public Health (2024) 24:1322

Telangana, Uttar Pradesh, and West Bengal are states
with High Prevalence and High Burden (headcount)
(Type IV) for both severely/moderately thin and mildly
thin in case of both men and women. Himachal Pradesh
and Tripura have Low Prevalence and Low Burden (Type
I).

On the other hand, the relationship between headcount
burden and prevalence of overweight and obese is not as
clear as thin populations. The distribution is similar for
overweight and ob
🧾 OCR scanning page 10...
Sung et al. BMC Public Health

(2024) 24:1322

A. Women

Page 10 of 12

z
2

Severely/Moderately Thin

Gorolane” Costlicirt, 053; p-o.ae
PACE) Tore Ik ow Palen H yh Burien .

; Tews Wh

neo. High Burden

raccece |

ova elit” Hacc. 1ss6t

Type Il. om Provalonce. H ah u'cen

Mildly Thin

Gowler on

rellcnerl 9463 9-060

12 HIgh Srevalanee 11. gh Auren

Tyo IL High Srevalenee Loser Pourcen

Overweight

9,6 80: § Guus

HM gh “evalence H gh durcer

MN ag Ih Lew Prowalcnice, Hag Burien

Obese

viutieg
🧾 OCR scanning page 11...
Sung et al. BMC Public Health (2024) 24:1322

education; and healthcare strengthening for providing
universal coverage of essential nutrition actions [37].

Additionally, gender differences in BMI are notable.
The gender differences in overweight/obesity in India can
be attributed to health risk factors, such as lower physi-
cal activity among women respondents [38]. Postpartum
weight retention could also cause higher reported over-
weight/obesity for women than in men [39]. Other con-
tributing
🧾 OCR scanning page 12...
Sung et al. BMC Public Health

20.

21.

22.

23.

(2024) 24:1322

CDC. Body Mass Index: Considerations for practitioners centers for dis-
ease control and prevention. 2021. https://www.cdc.gov/obesity/down|
oads/bmiforpactitioners.pdf. Accessed 13 May 2024.

WHO. The double burden of malnutrition: policy brief. World Health
Organization; 2016. https://www.who.int/publications/i/item/WHO-
NMH-NHD-17.3. Accessed 13 May 2024

Wells JC, Sawaya AL, Wibaek R, et al. The double burden of malnutri-
tio

In [18]:

#saved to csv and exported
import pandas as pd

tables = pd.read_excel(r"C:\Users\HP\Desktop\wegovy\India_Data.xlsx")
print(tables)
#then used this data to harcode the streamlit of states table

                       State_UT  severely/moderately thin  midly thin  \
0                         India                  29412236    50021199
1                   Maharashtra                   4230340     6131973
2                    Tamil Nadu                    937665     1524666
3                 Uttar Pradesh                   3008046     5880126
4                     Karnataka                   1710735     2932258
5                Andhra Pradesh                   1335625     2565458
6                       Gujarat                   3282370     4212620
7                   West Bengal                   2809375     5359771
8                         Bihar                   3252497     5771773
9                     Telangana                   1093889     1543634
10                       Kerala                    398898      681062
11                       Punjab                    286256      504282
12                    Rajasthan                   1177113     2237995
13               Madhya Pradesh                   1533256     2783973
14                       Odisha                    944406     1612549
15                        Assam                   1045960     1714708
16                    Jharkhand                    721597     1370640
17                      Haryana                    306388      542202
18                 Chhattisgarh                    648052     1249862
19             Himachal Pradesh                    109709      242221
20                  Uttarakhand                    108246      241272
21                          Goa                     38326       56997
22               NCT Delhi (UT)                    153339      320771
23                      Manipur                     19613       56945
24                      Tripura                     89955      182186
25              Puducherry (UT)                      9385       18286
26           Jammu&Kashmir (UT)                     55600      136214
27                      Mizoram                      4477       20066
28                    Meghalaya                     33462      105038
29                     Nagaland                     15576       37144
30                       Sikkim                      4201        6013
31                     Diu (UT)                     27367       32467
32            Arunachal Pradesh                      4104       10605
33              Chandigarh (UT)                     11527       12229
34                  Ladakh (UT)                       224        1748
35         Andaman&Nicobar (UT)                      3863        9221
36             Lakshadweep (UT)                      1149         422
37  Dadra and Nagar Haveli (UT)                      1387         422
38                          NaN                      1387         422

       normal  overweight     obese
0   389110427   137188470  37599029
1    49760520    17946442   4676538
2    13685429     8603768   3814678
3    41782446    13134006   3725632
4    25709842    12210878   3493421
5    18097616     9847329   3158123
6    26230139     7814417   2857348
7    50181013    13156564   2363263
8    36084214     9311491   1953691
9    11210183     5644159   1854102
10   10700571     6947211   1822809
11    4808473     2918016   1351680
12   19742074     3990390   1100044
13   16185098    38711435    970843
14    9355229     3167929    826694
15   16196011     3699860    691474
16    7441640     1453402    592603
17    4676904     2334501    581568
18    7441590     1504985    382653
19    2556529     1298155    302591
20    1871811      884256    205027
21     712838       39094     90498
22    3303468      815669     89699
23     942940      484162     87096
24    1826112      575520     78664
25     201934      159548     76508
26    4720630      233628     58976
27     447596      199545     43181
28    1523920      292010     35516
29     714911      228433     31927
30     247273      135334     26092
31     230410       78737     17167
32     263095       98250     16753
33     154566      102524      5827
34      86849       51192      5076
35     137994       52032      3279
36      25343       11498      2815
37      13467        2439       814
38      13467        2439       814

In [23]:
import camelot
import pandas as pd
import os

pdf_path = r"C:\Users\HP\Desktop\wegovy\prevelance.pdf"

def extract_tables_smart(pdf_path, show_preview=True, max_rows=10):
    """
    Extract tables from a PDF using both lattice and stream,
    then print them neatly in a structured format.
    """
    if not os.path.exists(pdf_path):
        print(f"❌ File not found: {pdf_path}")
        return []
    
    results = []
    for flavor in ["lattice", "stream"]:
        try:
            print(f"🔍 Trying {flavor} mode...")
            tables = camelot.read_pdf(pdf_path, pages="all", flavor=flavor)
            dfs = [t.df for t in tables if not t.df.empty]
            print(f"✅ {len(dfs)} non-empty tables found using {flavor}")
            results.extend(dfs)
        except Exception as e:
            print(f"⚠️ {flavor} failed: {e}")

    # Remove duplicates
    unique_tables = []
    seen = set()
    for df in results:
        key = (df.shape, df.head().to_string())
        if key not in seen:
            unique_tables.append(df)
            seen.add(key)

    print(f"\n📊 {len(unique_tables)} unique tables extracted.\n")

    # Optional structured display
    if show_preview:
        for i, df in enumerate(unique_tables):
            print("=" * 80)
            print(f"📄 Table {i+1} | Shape: {df.shape[0]} rows × {df.shape[1]} cols")
            print("-" * 80)
            # Clean up empty columns/rows for display
            df = df.dropna(how="all").replace(r"^\s*$", pd.NA, regex=True).dropna(how="all", axis=1)
            if len(df) > max_rows:
                display(df.head(max_rows))
                print(f"... (showing first {max_rows} rows)")
            else:
                display(df)
    return unique_tables

# Run and view structured tables
nfhs5_tables = {
    "BMC_PublicHealth": extract_tables_smart(pdf_path),
    "PLOS_ONE": []
}

🔍 Trying lattice mode...
✅ 7 non-empty tables found using lattice
🔍 Trying stream mode...

D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (53.12209632999997, 234.6434021, 544.1420963300002, 575.308619744009)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (170.544998168, 42.33909985299998, 548.7986981706749, 168.78634801500897)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692901610999996, 149.006393432, 540.9257016308322, 268.4828936668485)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692897883000015, 154.870803833, 543.541697876896, 267.67200378525)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

✅ 18 non-empty tables found using stream

📊 23 unique tables extracted.

================================================================================
📄 Table 1 | Shape: 2 rows × 2 cols
--------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1]

================================================================================
📄 Table 2 | Shape: 5 rows × 1 cols
--------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

================================================================================
📄 Table 3 | Shape: 5 rows × 3 cols
--------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

================================================================================
📄 Table 4 | Shape: 24 rows × 4 cols
--------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

... (showing first 10 rows)
================================================================================
📄 Table 5 | Shape: 4 rows × 4 cols
--------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

================================================================================
📄 Table 6 | Shape: 23 rows × 1 cols
--------------------------------------------------------------------------------

                                                   0
0                              S. V. Subramanian1,6*
1                                           Abstract
2  Background  The problem of overweight/obesity ...
3  and middle-income countries. BMI change in Ind...
4  Methods  This repeated cross-sectional study o...
5  categories of BMI among adults (age 20–54) in ...
6  2015–2016, and 2019–2021) for 36 states/UTs. S...
7  The categories were Severely/Moderately Thin (...
8  (25.0-29.9), and Obese (≥ 30.0). We also estim...
9  and headcount burden to quantify the trend of ...

... (showing first 10 rows)
================================================================================
📄 Table 7 | Shape: 8 rows × 1 cols
--------------------------------------------------------------------------------

                                                   0
0  © The Author(s) 2024. Open Access This article...
1  permits use, sharing, adaptation, distribution...
2  original author(s) and the source, provide a l...
3  other third party material in this article are...
4  to the material. If material is not included i...
5  regulation or exceeds the permitted use, you w...
6  licence, visit http://creativecommons.org/lice...
7  mons.org/publicdomain/zero/1.0/) applies to th...

================================================================================
📄 Table 8 | Shape: 56 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,Background,<NA>
1,<NA>,(NFHS-5) or did not analyze the change ...
2,The Sustainable Development Goal (SDG) 2 seeks...,over 20 years using a representative public da...
3,"hunger and ensure access to safe, nutrit...",is also a dearth of literature focusing ...
4,cient food year-round by 2030. The SDG 3 aims ...,difference in BMI outcomes. (Additional file 1...
5,healthy lives and promote wellbeing for all at...,S1).
6,It is important to evaluate the nutritional st...,"In this study, we present an up-to-date ..."
7,effective policies to ascertain these goa...,hensive description of the trends in the preva...
8,Index (BMI) serves as a good metric for evalua...,ferent BMI categories among adults in In...
9,ulation-level nutritional status and futur...,states/UTs between 1999 and 2021. We use...

... (showing first 10 rows)
================================================================================
📄 Table 9 | Shape: 58 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,Recode dataset for men as BMI data was not pre...,time whereas a positive SAC value indicates ri...
1,the individual interview data for men.,lence during this period.
2,<NA>,We used box plots and heat tables to assess th...
3,Study population,<NA>
4,<NA>,to which \nstate \ninequalities \nin BMI ou...
5,The study population was adult women aged 20–4...,increased/decreased over time. Descriptive ...
6,who were not currently pregnant and had not gi...,of the state-level patterns over time we...
7,"in the last two months, and men aged 2...",scatterplots and correlations. Specifically...
8,lived in households that were selected for the...,whether the magnitude and patterns of ch...
9,ule. Men’s data was not collected in th...,related with the prevalence of BMI outco...

... (showing first 10 rows)
================================================================================
📄 Table 10 | Shape: 9 rows × 7 cols
--------------------------------------------------------------------------------

,0,1,2,3,4,5,6
0,<NA>,Table 1 Study sample size selection from the ...,<NA>,<NA>,<NA>,<NA>,<NA>
1,Survey round (Year),<NA>,Sample size based on inclusion,<NA>,"Missing or implausible values (n , (%))",Final study sample size,<NA>
2,<NA>,criteria (n),<NA>,<NA>,<NA>,<NA>,<NA>
3,<NA>,Women,Men,Women,Men,Women,Men
4,NFHS-2(1998-99),"76,880",-,"5,495 (7.1)",-,"71,385",-
5,NFHS-3(2005-06),"94,575","74,572","4,242 (4.5)","15,637 (26.5)","90,333","58,935"
6,NFHS-4(2015-16),"540,840","105,351","9,407 (1.7)","12,777 (13.8)","531,433","92,574"
7,NFHS-5(2019-21),"569,203","95,726","18,176 (3.2)","13,528 (16.5)","551,027","82,198"
8,All waves,"1,281,498","270,814","37,320 (2.9)","37,107 (13.7)","1,244,178","233,707"

================================================================================
📄 Table 11 | Shape: 7 rows × 1 cols
--------------------------------------------------------------------------------

                                                   0
0  Fig. 1  Comparative Distribution of Body Mass ...
1  both panels (A) and (B), the upper bar represe...
2  for the latest period (2021). The cutoff point...
3  Overweight (25.0-29.9), and Obese ( ≥30.0) A W...
4  Nicobar, Chandigarh, Dadra and Nagar Haveli an...
5  B Men. The earliest survey period for Andaman ...
6  earliest survey period for all other states is...

================================================================================
📄 Table 12 | Shape: 6 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,earliest survey period for all other states is...,<NA>
1,(absolute change: women + 1.2%; men + 1.2%)...,or moderate thinness in urban India in ...
2,Figs. 1 and 2).,"for women and 2.5% for men, whereas in ..."
3,Rural areas consistently show a higher rate of...,"these figures rose to 6.2% and 3.5%, re..."
4,"compared to urban areas, which exhibit greater...","versely, obesity rates were higher in urban se..."
5,"of overweight and obesity. For instance, the r...",11.0% of women and 6.6% of men being affected ...

================================================================================
📄 Table 13 | Shape: 5 rows × 2 cols
--------------------------------------------------------------------------------

                                                   0             1
0  Sung et al. BMC Public Health         (2024) 2...  Page 5 of 12
1  Fig. 2  Summary distribution of state/Union Te...          <NA>
2  shows the variability of a data set using lowe...          <NA>
3  and maximum values, respectively. The upper ou...          <NA>
4  within the box (separating the darker and ligh...          <NA>

================================================================================
📄 Table 14 | Shape: 23 rows × 9 cols
--------------------------------------------------------------------------------

,0,1,2,3,4,5,6,7,8
0,divided by,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Height^2),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,<NA>,Severely /Moderately Thin (< 17.0),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,All,<NA>,"9,647 (13.5%)","10,384 (11.5%)","38,536 (7.3%)","30,424 (5.5%)","4,909 (8.3%)","4,296 (4.6%)","2,645 (3.2%)"
4,Urban,<NA>,"1,958 (8.4%)","3,296 (8.0%)","7,165 (4.5%)","4,906 (3.5%)","1,967 (6.7%)","1,070 (3.7%)",517 (2.5%)
5,Rural,<NA>,"7,689 (16.0%)","7,088 (14.5%)","31,371 (8.4%)","25,518 (6.2%)","2,942 (10.0%)","3,226 (5.1%)","2,128 (3.5%)"
6,<NA>,Mildly Thin (17.0-18.4),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,All,<NA>,"12,963 (18.2%)","13,683 (15.1%)","60,255 (11.3%)","47,791 (8.7%)","8,925 (15.1%)","9,094 (9.8%)","5,611 (6.8%)"
8,Urban,<NA>,"2,736 (11.7%)","4,327 (10.5%)","11,300 (7.1%)","7,554 (5.4%)","3,397 (11.5%)","1,934 (6.7%)",955 (4.5%)
9,Rural,<NA>,"10,227 (21.3%)","9,356 (19.1%)","48,955 (13.1%)","40,237 (9.8%)","5,528 (18.7%)","7,160 (11.3%)","4,656 (7.6%)"

... (showing first 10 rows)
================================================================================
📄 Table 15 | Shape: 28 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,"Rural\n568 (1.2%)\n887 (1.8%)\n12,530 (3.4%)","19,718 (4.8%)\n246 (0.8%)\n1,391 (2.2%)\n2,031..."
1,compared to 4.8% of women and 3.3% of ...,"Madhya Pradesh, \nand Tripura) \nshowed \nan..."
2,locations. The patterns of BMI change \nf...,between 1999 and 2006. Obesity substantia...
3,urban populations followed the overall trend o...,"in Tamil Nadu (SAC 1999–2021: 0.58%), Andhra P..."
4,ing thinness and increasing overweight/obesity...,"(0.49%), and Haryana (0.34%) (Fig. 3, Fi..."
5,"Figure S1, Figure S2).",S4 shows the detailed SAC between each survey ...
6,More than half of the population consistently ...,Trends for men were similar to those in...
7,"sified as “Normal” BMI, ranging from 55 to 65%...",the prevalence of extreme categories (sev...
8,<NA>,ately thin and obese) was less than for...
9,Changes in the geographic distribution of BMI ...,<NA>

... (showing first 10 rows)
================================================================================
📄 Table 16 | Shape: 6 rows × 1 cols
--------------------------------------------------------------------------------

                                                   0
0  Fig. 3  Standardized Absolute Change (SAC, per...
1  across States/Union Territories. A Women, SAC ...
2  and Nagar Haveli and Daman and Diu, Lakshadwee...
3  in the NFHS survey in 1999. B Men, SAC from 20...
4  and Daman and Diu, Lakshadweep, and Puducherry...
5                                            in 2006

================================================================================
📄 Table 17 | Shape: 9 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,"and Daman and Diu, Lakshadweep, and Puducherry...",<NA>
1,in 2006,<NA>
2,<NA>,Estimated headcount of BMI outcomes in India
3,between the rankings across years. A correlati...,<NA>
4,1 indicates the ranking of states has n...,"In 2021, approximately 29,412,236 adults were ..."
5,over time and a smaller value suggests ...,moderately thin in India (Fig. 4). The populat...
6,ranking (Table S2). The rank correlation ...,"count varied from 4,230,340 in Maharashtr..."
7,ordering of states/UTs was strong (> 0.7) for ...,"Ladakh. Maharashtra (13.94%), Gujarat (10.82%)..."
8,except normal BMI for both women and men.,<NA>

================================================================================
📄 Table 18 | Shape: 10 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,separately and summed up to estimate values fo...,<NA>
1,shades representing a larger proportion,<NA>
2,(10.72%) and Uttar Pradesh (9.91%) account for...,States/UTs with a higher prevalence of t...
3,of the total burden of severely/moderately thi...,"average, tend to have a larger absolute ..."
4,"In 2021, approximately 37,599,029 adults ...",men \nand women \n(severely/moderately \nthin...
5,in \nIndia \n(Fig. 4). The population head...,"r = 0.59, men r = 0.60; mildly thin: wome..."
6,"from 4,676,538 \nin Maharashtra to 2,815 \...",r = 0.55) (Fig. 5). Distributions of states fo...
7,"weep. Maharashtra (12.05%), Tamil Nadu (9...",erately thin and mildly thin resemble each oth...
8,"Pradesh \n(9.60%), and Karnataka \n(9.00%) ...","Pradesh, Assam, Bihar, Chhattisgarh, Gujarat, ..."
9,40.48% of the total burden of obesity in India.,"Karnataka, Madhya \nPradesh, Maharashtra, O..."

================================================================================
📄 Table 19 | Shape: 46 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,"Telangana, Uttar Pradesh, and West Bengal...","of reproductive age, our study offers in..."
1,with High Prevalence and High Burden \n(h...,prevalence of both underweight and overwe...
2,(Type IV) for both severely/moderately th...,sity conditions across Indian states for ...
3,thin in case of both men and women. Himachal P...,women.
4,and Tripura have Low Prevalence and Low Burden...,There were several limitations of the st...
5,I).,absence of data on men in the NFHS-2 survey (1...
6,"On the other hand, the relationship between he...",complicates the gender comparison over th...
7,burden and prevalence of overweight and obese ...,"ond, the NFHS-5, initiated in 2019, encountere..."
8,clear as thin populations. The distributi...,"tions due to the COVID-19 pandemic, whic..."
9,overweight and obesity for both genders. ...,the continuity and comprehensiveness of t...

... (showing first 10 rows)
================================================================================
📄 Table 20 | Shape: 2 rows × 2 cols
--------------------------------------------------------------------------------

                                                   0              1
0  Sung et al. BMC Public Health         (2024) 2...  Page 10 of 12
1            Fig. 5 \n(See legend on previous page.)           <NA>

================================================================================
📄 Table 21 | Shape: 74 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,<NA>,WHO \nWorld health organization
1,education; and healthcare strengthening fo...,<NA>
2,<NA>,SAC \nStandardized absolute change
3,universal coverage of essential nutrition acti...,IPUMS \nIntegrated public use microdata series
4,"Additionally, gender differences in BMI a...",EAG \nEmpowered action group states
5,The gender differences in overweight/obesity i...,<NA>
6,"be attributed to health risk factors, such as ...",Supplementary Information
7,cal activity among women respondents [38]. Pos...,The online version contains supplementary mate...
8,<NA>,org/ 10. 1186/ s12889- 024- 18784-4.
9,weight retention could also cause higher ...,<NA>

... (showing first 10 rows)
================================================================================
📄 Table 22 | Shape: 9 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,and develop new interventions to target ...,<NA>
1,malnutrition.,<NA>
2,Abbreviations,References
3,BMI \nBody mass index,1. \nUNDP. The SDGs In Action: United nations...
4,NFHS \nNational family health survey,2022.https:// www. undp. org/ africa/ waca/ sd...
5,UT \nUnion territories,2024.
6,SDG \nSustainable development goal,<NA>
7,LMIC \nLow- and middle- income countries,<NA>
8,DBM \nDouble burden of malnutrition,<NA>

================================================================================
📄 Table 23 | Shape: 72 rows × 2 cols
--------------------------------------------------------------------------------

,0,1
0,2. \nCDC. Body Mass Index: Considerations for...,24. \nInternational Institute for Population ...
1,ease control and prevention. 2021. https:// ww...,"Family Health Survey (NFHS-2), 1998–99: India...."
2,oads/ bmifo rpact ition ers. pdf. Accessed 13 ...,dhspr ogram. com/ pubs/ pdf/ frind2/ frind2. p...
3,3. WHO. The double burden of malnutrition: p...,25. \nInternational Institute for Population ...
4,Organization; 2016. https:// www. who. int/ pu...,"Family Health Survey (NFHS-3), 2005–06: India...."
5,NMH- NHD- 17.3. Accessed 13 May 2024,dhspr ogram. com/ pubs/ pdf/ frind3/ frind3- v...
6,"4. Wells JC, Sawaya AL, Wibaek R, et al. The...",May 2024.
7,tion: aetiological pathways and consequences f...,26. \nInternational Institute for Population ...
8,2020;395(10217):75–88.,"Family Health Survey (NFHS-4), 2015-16: India...."
9,"5. \nPopkin BM, Corvalan C, Grummer-Strawn LM...",ogram. com/ pubs/ pdf/ fr339/ fr339. pdf. Acce...

... (showing first 10 rows)

In [26]:
# ================================================================
# 📊 NFHS-5 PDF → Clean Obesity Data Pipeline
# ================================================================
import os, re, camelot, pandas as pd
from IPython.display import display

# ------------------------------------------------
# 1️⃣ Extract tables from PDF (both lattice & stream)
# ------------------------------------------------
pdf_path = r"C:\Users\HP\Desktop\wegovy\prevelance.pdf"

def extract_tables_smart(pdf_path, show_preview=True, max_rows=8):
    """Extract tables using both lattice & stream modes, print structured output."""
    if not os.path.exists(pdf_path):
        print(f"❌ File not found: {pdf_path}")
        return []

    results = []
    for flavor in ["lattice", "stream"]:
        try:
            print(f"🔍 Trying {flavor} mode...")
            tables = camelot.read_pdf(pdf_path, pages="all", flavor=flavor)
            dfs = [t.df for t in tables if not t.df.empty]
            print(f"✅ {len(dfs)} non-empty tables found using {flavor}")
            results.extend(dfs)
        except Exception as e:
            print(f"⚠️ {flavor} failed: {e}")

    # remove duplicates
    unique_tables, seen = [], set()
    for df in results:
        key = (df.shape, df.head().to_string())
        if key not in seen:
            unique_tables.append(df)
            seen.add(key)

    print(f"\n📊 {len(unique_tables)} unique tables extracted.\n")

    if show_preview:
        for i, df in enumerate(unique_tables):
            print("=" * 90)
            print(f"📄 Table {i+1} | Shape: {df.shape[0]} rows × {df.shape[1]} cols")
            print("-" * 90)
            df = df.dropna(how="all").replace(r"^\s*$", pd.NA, regex=True).dropna(how="all", axis=1)
            display(df.head(max_rows))
    return unique_tables


# ------------------------------------------------
# 2️⃣ Identify BMI/Obesity-related table
# ------------------------------------------------
def find_bmi_table(table_list):
    for i, df in enumerate(table_list):
        if df.astype(str).apply(lambda x: x.str.contains("Obese|BMI", case=False)).any().any():
            print(f"✅ Found BMI/Obesity table at index {i}")
            return df
    print("❌ No BMI-related table found.")
    return None


# ------------------------------------------------
# 3️⃣ Extract and clean obesity data from the table
# ------------------------------------------------
def extract_state_obesity(df):
    pattern = r"(Men|Women).*Obese|BMI"
    # detect 'State/UT' column
    state_col = next((c for c in df.columns if re.search(r"state|ut", str(c), re.IGNORECASE)), df.columns[0])
    cols = [c for c in df.columns if re.search(pattern, str(c), re.IGNORECASE)]
    if not cols:
        print("⚠️ Could not find obesity-related columns.")
        print(f"Available columns: {list(df.columns)}")
        return pd.DataFrame()
    sub = df[[state_col] + cols].copy()
    sub.columns = ["State/UT"] + [re.sub(r"[^A-Za-z_]", "_", c) for c in cols]
    sub = sub.replace(r"^\s*$", pd.NA, regex=True).dropna(how="all")
    sub["State/UT"] = sub["State/UT"].str.strip()
    print(f"✅ Extracted obesity data for {len(sub)} states/regions.")
    return sub


# ------------------------------------------------
# 🚀 Run the pipeline
# ------------------------------------------------
nfhs5_tables = {"BMC_PublicHealth": extract_tables_smart(pdf_path)}
bmc_table = find_bmi_table(nfhs5_tables["BMC_PublicHealth"])

if bmc_table is not None and not bmc_table.empty:
    obesity_df = extract_state_obesity(bmc_table)
    display(obesity_df.head())
else:
    print("⚠️ No valid BMI table found to extract obesity data.")

🔍 Trying lattice mode...
✅ 7 non-empty tables found using lattice
🔍 Trying stream mode...

D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (53.12209632999997, 234.6434021, 544.1420963300002, 575.308619744009)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (170.544998168, 42.33909985299998, 548.7986981706749, 168.78634801500897)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692901610999996, 149.006393432, 540.9257016308322, 268.4828936668485)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
D:\anoconda\envs\newenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (52.692897883000015, 154.870803833, 543.541697876896, 267.67200378525)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

✅ 18 non-empty tables found using stream

📊 23 unique tables extracted.

==========================================================================================
📄 Table 1 | Shape: 2 rows × 2 cols
------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1]

==========================================================================================
📄 Table 2 | Shape: 5 rows × 1 cols
------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

==========================================================================================
📄 Table 3 | Shape: 5 rows × 3 cols
------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

==========================================================================================
📄 Table 4 | Shape: 24 rows × 4 cols
------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

==========================================================================================
📄 Table 5 | Shape: 4 rows × 4 cols
------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

==========================================================================================
📄 Table 6 | Shape: 23 rows × 1 cols
------------------------------------------------------------------------------------------

                                                   0
0                              S. V. Subramanian1,6*
1                                           Abstract
2  Background  The problem of overweight/obesity ...
3  and middle-income countries. BMI change in Ind...
4  Methods  This repeated cross-sectional study o...
5  categories of BMI among adults (age 20–54) in ...
6  2015–2016, and 2019–2021) for 36 states/UTs. S...
7  The categories were Severely/Moderately Thin (...

==========================================================================================
📄 Table 7 | Shape: 8 rows × 1 cols
------------------------------------------------------------------------------------------

                                                   0
0  © The Author(s) 2024. Open Access This article...
1  permits use, sharing, adaptation, distribution...
2  original author(s) and the source, provide a l...
3  other third party material in this article are...
4  to the material. If material is not included i...
5  regulation or exceeds the permitted use, you w...
6  licence, visit http://creativecommons.org/lice...
7  mons.org/publicdomain/zero/1.0/) applies to th...

==========================================================================================
📄 Table 8 | Shape: 56 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,Background,<NA>
1,<NA>,(NFHS-5) or did not analyze the change ...
2,The Sustainable Development Goal (SDG) 2 seeks...,over 20 years using a representative public da...
3,"hunger and ensure access to safe, nutrit...",is also a dearth of literature focusing ...
4,cient food year-round by 2030. The SDG 3 aims ...,difference in BMI outcomes. (Additional file 1...
5,healthy lives and promote wellbeing for all at...,S1).
6,It is important to evaluate the nutritional st...,"In this study, we present an up-to-date ..."
7,effective policies to ascertain these goa...,hensive description of the trends in the preva...

==========================================================================================
📄 Table 9 | Shape: 58 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,Recode dataset for men as BMI data was not pre...,time whereas a positive SAC value indicates ri...
1,the individual interview data for men.,lence during this period.
2,<NA>,We used box plots and heat tables to assess th...
3,Study population,<NA>
4,<NA>,to which \nstate \ninequalities \nin BMI ou...
5,The study population was adult women aged 20–4...,increased/decreased over time. Descriptive ...
6,who were not currently pregnant and had not gi...,of the state-level patterns over time we...
7,"in the last two months, and men aged 2...",scatterplots and correlations. Specifically...

==========================================================================================
📄 Table 10 | Shape: 9 rows × 7 cols
------------------------------------------------------------------------------------------

,0,1,2,3,4,5,6
0,<NA>,Table 1 Study sample size selection from the ...,<NA>,<NA>,<NA>,<NA>,<NA>
1,Survey round (Year),<NA>,Sample size based on inclusion,<NA>,"Missing or implausible values (n , (%))",Final study sample size,<NA>
2,<NA>,criteria (n),<NA>,<NA>,<NA>,<NA>,<NA>
3,<NA>,Women,Men,Women,Men,Women,Men
4,NFHS-2(1998-99),"76,880",-,"5,495 (7.1)",-,"71,385",-
5,NFHS-3(2005-06),"94,575","74,572","4,242 (4.5)","15,637 (26.5)","90,333","58,935"
6,NFHS-4(2015-16),"540,840","105,351","9,407 (1.7)","12,777 (13.8)","531,433","92,574"
7,NFHS-5(2019-21),"569,203","95,726","18,176 (3.2)","13,528 (16.5)","551,027","82,198"

==========================================================================================
📄 Table 11 | Shape: 7 rows × 1 cols
------------------------------------------------------------------------------------------

                                                   0
0  Fig. 1  Comparative Distribution of Body Mass ...
1  both panels (A) and (B), the upper bar represe...
2  for the latest period (2021). The cutoff point...
3  Overweight (25.0-29.9), and Obese ( ≥30.0) A W...
4  Nicobar, Chandigarh, Dadra and Nagar Haveli an...
5  B Men. The earliest survey period for Andaman ...
6  earliest survey period for all other states is...

==========================================================================================
📄 Table 12 | Shape: 6 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,earliest survey period for all other states is...,<NA>
1,(absolute change: women + 1.2%; men + 1.2%)...,or moderate thinness in urban India in ...
2,Figs. 1 and 2).,"for women and 2.5% for men, whereas in ..."
3,Rural areas consistently show a higher rate of...,"these figures rose to 6.2% and 3.5%, re..."
4,"compared to urban areas, which exhibit greater...","versely, obesity rates were higher in urban se..."
5,"of overweight and obesity. For instance, the r...",11.0% of women and 6.6% of men being affected ...

==========================================================================================
📄 Table 13 | Shape: 5 rows × 2 cols
------------------------------------------------------------------------------------------

                                                   0             1
0  Sung et al. BMC Public Health         (2024) 2...  Page 5 of 12
1  Fig. 2  Summary distribution of state/Union Te...          <NA>
2  shows the variability of a data set using lowe...          <NA>
3  and maximum values, respectively. The upper ou...          <NA>
4  within the box (separating the darker and ligh...          <NA>

==========================================================================================
📄 Table 14 | Shape: 23 rows × 9 cols
------------------------------------------------------------------------------------------

,0,1,2,3,4,5,6,7,8
0,divided by,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Height^2),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,<NA>,Severely /Moderately Thin (< 17.0),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,All,<NA>,"9,647 (13.5%)","10,384 (11.5%)","38,536 (7.3%)","30,424 (5.5%)","4,909 (8.3%)","4,296 (4.6%)","2,645 (3.2%)"
4,Urban,<NA>,"1,958 (8.4%)","3,296 (8.0%)","7,165 (4.5%)","4,906 (3.5%)","1,967 (6.7%)","1,070 (3.7%)",517 (2.5%)
5,Rural,<NA>,"7,689 (16.0%)","7,088 (14.5%)","31,371 (8.4%)","25,518 (6.2%)","2,942 (10.0%)","3,226 (5.1%)","2,128 (3.5%)"
6,<NA>,Mildly Thin (17.0-18.4),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,All,<NA>,"12,963 (18.2%)","13,683 (15.1%)","60,255 (11.3%)","47,791 (8.7%)","8,925 (15.1%)","9,094 (9.8%)","5,611 (6.8%)"

==========================================================================================
📄 Table 15 | Shape: 28 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,"Rural\n568 (1.2%)\n887 (1.8%)\n12,530 (3.4%)","19,718 (4.8%)\n246 (0.8%)\n1,391 (2.2%)\n2,031..."
1,compared to 4.8% of women and 3.3% of ...,"Madhya Pradesh, \nand Tripura) \nshowed \nan..."
2,locations. The patterns of BMI change \nf...,between 1999 and 2006. Obesity substantia...
3,urban populations followed the overall trend o...,"in Tamil Nadu (SAC 1999–2021: 0.58%), Andhra P..."
4,ing thinness and increasing overweight/obesity...,"(0.49%), and Haryana (0.34%) (Fig. 3, Fi..."
5,"Figure S1, Figure S2).",S4 shows the detailed SAC between each survey ...
6,More than half of the population consistently ...,Trends for men were similar to those in...
7,"sified as “Normal” BMI, ranging from 55 to 65%...",the prevalence of extreme categories (sev...

==========================================================================================
📄 Table 16 | Shape: 6 rows × 1 cols
------------------------------------------------------------------------------------------

                                                   0
0  Fig. 3  Standardized Absolute Change (SAC, per...
1  across States/Union Territories. A Women, SAC ...
2  and Nagar Haveli and Daman and Diu, Lakshadwee...
3  in the NFHS survey in 1999. B Men, SAC from 20...
4  and Daman and Diu, Lakshadweep, and Puducherry...
5                                            in 2006

==========================================================================================
📄 Table 17 | Shape: 9 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,"and Daman and Diu, Lakshadweep, and Puducherry...",<NA>
1,in 2006,<NA>
2,<NA>,Estimated headcount of BMI outcomes in India
3,between the rankings across years. A correlati...,<NA>
4,1 indicates the ranking of states has n...,"In 2021, approximately 29,412,236 adults were ..."
5,over time and a smaller value suggests ...,moderately thin in India (Fig. 4). The populat...
6,ranking (Table S2). The rank correlation ...,"count varied from 4,230,340 in Maharashtr..."
7,ordering of states/UTs was strong (> 0.7) for ...,"Ladakh. Maharashtra (13.94%), Gujarat (10.82%)..."

==========================================================================================
📄 Table 18 | Shape: 10 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,separately and summed up to estimate values fo...,<NA>
1,shades representing a larger proportion,<NA>
2,(10.72%) and Uttar Pradesh (9.91%) account for...,States/UTs with a higher prevalence of t...
3,of the total burden of severely/moderately thi...,"average, tend to have a larger absolute ..."
4,"In 2021, approximately 37,599,029 adults ...",men \nand women \n(severely/moderately \nthin...
5,in \nIndia \n(Fig. 4). The population head...,"r = 0.59, men r = 0.60; mildly thin: wome..."
6,"from 4,676,538 \nin Maharashtra to 2,815 \...",r = 0.55) (Fig. 5). Distributions of states fo...
7,"weep. Maharashtra (12.05%), Tamil Nadu (9...",erately thin and mildly thin resemble each oth...

==========================================================================================
📄 Table 19 | Shape: 46 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,"Telangana, Uttar Pradesh, and West Bengal...","of reproductive age, our study offers in..."
1,with High Prevalence and High Burden \n(h...,prevalence of both underweight and overwe...
2,(Type IV) for both severely/moderately th...,sity conditions across Indian states for ...
3,thin in case of both men and women. Himachal P...,women.
4,and Tripura have Low Prevalence and Low Burden...,There were several limitations of the st...
5,I).,absence of data on men in the NFHS-2 survey (1...
6,"On the other hand, the relationship between he...",complicates the gender comparison over th...
7,burden and prevalence of overweight and obese ...,"ond, the NFHS-5, initiated in 2019, encountere..."

==========================================================================================
📄 Table 20 | Shape: 2 rows × 2 cols
------------------------------------------------------------------------------------------

                                                   0              1
0  Sung et al. BMC Public Health         (2024) 2...  Page 10 of 12
1            Fig. 5 \n(See legend on previous page.)           <NA>

==========================================================================================
📄 Table 21 | Shape: 74 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,<NA>,WHO \nWorld health organization
1,education; and healthcare strengthening fo...,<NA>
2,<NA>,SAC \nStandardized absolute change
3,universal coverage of essential nutrition acti...,IPUMS \nIntegrated public use microdata series
4,"Additionally, gender differences in BMI a...",EAG \nEmpowered action group states
5,The gender differences in overweight/obesity i...,<NA>
6,"be attributed to health risk factors, such as ...",Supplementary Information
7,cal activity among women respondents [38]. Pos...,The online version contains supplementary mate...

==========================================================================================
📄 Table 22 | Shape: 9 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,and develop new interventions to target ...,<NA>
1,malnutrition.,<NA>
2,Abbreviations,References
3,BMI \nBody mass index,1. \nUNDP. The SDGs In Action: United nations...
4,NFHS \nNational family health survey,2022.https:// www. undp. org/ africa/ waca/ sd...
5,UT \nUnion territories,2024.
6,SDG \nSustainable development goal,<NA>
7,LMIC \nLow- and middle- income countries,<NA>

==========================================================================================
📄 Table 23 | Shape: 72 rows × 2 cols
------------------------------------------------------------------------------------------

,0,1
0,2. \nCDC. Body Mass Index: Considerations for...,24. \nInternational Institute for Population ...
1,ease control and prevention. 2021. https:// ww...,"Family Health Survey (NFHS-2), 1998–99: India...."
2,oads/ bmifo rpact ition ers. pdf. Accessed 13 ...,dhspr ogram. com/ pubs/ pdf/ frind2/ frind2. p...
3,3. WHO. The double burden of malnutrition: p...,25. \nInternational Institute for Population ...
4,Organization; 2016. https:// www. who. int/ pu...,"Family Health Survey (NFHS-3), 2005–06: India...."
5,NMH- NHD- 17.3. Accessed 13 May 2024,dhspr ogram. com/ pubs/ pdf/ frind3/ frind3- v...
6,"4. Wells JC, Sawaya AL, Wibaek R, et al. The...",May 2024.
7,tion: aetiological pathways and consequences f...,26. \nInternational Institute for Population ...

✅ Found BMI/Obesity table at index 5
⚠️ Could not find obesity-related columns.
Available columns: [0]

Empty DataFrame
Columns: []
Index: []

In [27]:
# Cell 6: Plot obesity prevalence by state
import plotly.express as px

if not obesity_df.empty:
    fig = px.bar(
        obesity_df,
        x="State/UT",
        y=obesity_df.columns[1],
        title="NFHS-5 Obesity Prevalence by State (Extracted)",
        text=obesity_df.columns[1]
    )
    fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
    fig.update_layout(xaxis_tickangle=-45, height=500)
    fig.show()

In [58]:
# ================== Full Content Extraction from URLs (HTML + PDF) ==================

import requests
from bs4 import BeautifulSoup
import pandas as pd
import io
import sys

# Ensure html5lib is installed
try:
    import html5lib
except ImportError:
    print("html5lib not found. Install with: pip install html5lib")
    sys.exit(1)

# Optional: PDF extraction library
try:
    from PyPDF2 import PdfReader
except ImportError:
    print("PyPDF2 not found. Install with: pip install PyPDF2")
    sys.exit(1)

urls = {
    "market_growth_rate": "https://www.grandviewresearch.com/industry-analysis/glp-1-obesity-market",
    "market_value_cr": "https://www.economictimes.indiatimes.com/nonexistent-page",
    "patient_acceptance": "https://www.iosrjournals.org/papers/patient-acceptance-of-glp1.pdf",
    "bariatric_cost_range": "https://www.nobesity.in/nonexistent-page"
}

results = {}

for key, url in urls.items():
    print(f"\nProcessing {key} -> {url}")
    try:
        r = requests.get(url)
        if r.status_code != 200:
            results[key] = {"error": f"HTTP {r.status_code} - Page not found"}
            continue

        if url.endswith(".pdf"):
            # Extract full PDF text
            try:
                reader = PdfReader(io.BytesIO(r.content))
                full_text = ""
                for page in reader.pages:
                    text = page.extract_text()
                    if text:
                        full_text += text + "\n"
                results[key] = {"pdf_full_text": full_text.strip()}
            except Exception as e:
                results[key] = {"error": f"PDF extraction failed: {e}"}
        else:
            # Extract full HTML text and numeric tables
            soup = BeautifulSoup(r.content, "html.parser")

            # Full text
            full_text = soup.get_text(separator="\n").strip()

            # Extract all tables
            try:
                tables = pd.read_html(r.text)
                table_texts = []
                for idx, table in enumerate(tables):
                    table_texts.append(f"Table {idx+1}:\n{table.to_string(index=False)}")
            except ValueError:
                table_texts = []

            results[key] = {
                "html_full_text": full_text,
                "tables_text": table_texts
            }

    except Exception as e:
        results[key] = {"error": str(e)}

# Print results for inspection (you can also save to file)
for k, v in results.items():
    print(f"\n===== {k} =====")
    if "error" in v:
        print("Error:", v["error"])
    if "pdf_full_text" in v:
        print(v["pdf_full_text"][:1000], "...")  # first 1000 chars
    if "html_full_text" in v:
        print(v["html_full_text"][:1000], "...")  # first 1000 chars
    if "tables_text" in v and v["tables_text"]:
        for t in v["tables_text"]:
            print(t, "\n")

Processing market_growth_rate -> https://www.grandviewresearch.com/industry-analysis/glp-1-obesity-market

C:\Users\HP\AppData\Local\Temp\ipykernel_11888\1746315206.py:61: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(r.text)

Processing market_value_cr -> https://www.economictimes.indiatimes.com/nonexistent-page

Processing patient_acceptance -> https://www.iosrjournals.org/papers/patient-acceptance-of-glp1.pdf

Processing bariatric_cost_range -> https://www.nobesity.in/nonexistent-page

===== market_growth_rate =====
Grand View Research


















































































Grand View Research Logo
































Toggle navigation


















Reports








Consumer Goods »


Beauty & Personal Care


Clothing, Footwear & Accessories


Consumer F&B


Electronic & Electrical


Homecare & Decor










Semiconductors & Electronics »


Display Technologies


Electronic Security Systems


Electronic Devices


Semiconductors


Sensors & Controls










Specialty & Fine Chemicals »


Catalysts and Enzymes


Food Additives and Nutricosmetics


Renewable Chemicals


Specialty and Bio-based Polymers










Food & Beverages »


Animal Feed & Feed Additives


Food Safety & Processing


Nutraceuticals & Functional Foods


Processed & Frozen Foods










Advanced Materials »


Advanced Interior Materials


Green Building Materials


Micro Molding and Microspheres


Nanoparticles


Smart Textiles


Glass, Ceramics and Fibers







 ...

===== market_value_cr =====
Error: HTTP 404 - Page not found

===== patient_acceptance =====
Error: HTTP 404 - Page not found

===== bariatric_cost_range =====
Error: HTTP 404 - Page not found

In [29]:
# ✅ Fixed version: Extract tables from the correct PDF file
import camelot
import os

# Correct file path
pdf_path = r"C:\Users\HP\Desktop\wegovy\prevelance.pdf"

# Ensure the file exists
if not os.path.exists(pdf_path):
    raise FileNotFoundError(f"❌ PDF file not found at: {pdf_path}")

# Extract tables using lattice mode first
print(f"📄 Extracting tables from: {pdf_path}")
tables = camelot.read_pdf(pdf_path, pages='all', flavor='lattice')

print(f"✅ Found {len(tables)} tables using lattice mode")

# If no tables found, try stream mode as fallback
if len(tables) == 0:
    print("⚠️ Lattice mode found no tables — trying stream mode...")
    tables = camelot.read_pdf(pdf_path, pages='all', flavor='stream')
    print(f"✅ Found {len(tables)} tables using stream mode")

# Display extracted tables neatly
if len(tables) > 0:
    for i, table in enumerate(tables):
        print(f"\n--- Table {i+1} | Shape: {table.df.shape} ---")
        display(table.df.head(10))
else:
    print("❌ No tables could be extracted from the PDF.")

📄 Extracting tables from: C:\Users\HP\Desktop\wegovy\prevelance.pdf
✅ Found 7 tables using lattice mode

--- Table 1 | Shape: (2, 2) ---

  0 1
0
1

--- Table 2 | Shape: (2, 2) ---

  0 1
0
1

--- Table 3 | Shape: (5, 1) ---

  0
0
1
2
3
4

--- Table 4 | Shape: (5, 3) ---

  0 1 2
0
1
2
3
4

--- Table 5 | Shape: (24, 4) ---

  0 1 2 3
0
1
2
3
4
5
6
7
8
9

--- Table 6 | Shape: (4, 4) ---

  0 1 2 3
0
1
2
3

--- Table 7 | Shape: (4, 4) ---

  0 1 2 3
0
1
2
3

In [60]:
# Cell 7: Build unified dataset
results = {
    "nfhs_tables_found": len(nfhs_tables),
    "nfhs_preview": nfhs_df.head().to_dict() if not nfhs_df.empty else None,
    "treatment_sources": treatment_data
}

# Display JSON summary
print(json.dumps(results, indent=2)[:2000])

{
  "nfhs_tables_found": 0,
  "nfhs_preview": null,
  "treatment_sources": [
    {
      "url": "https://www.grandviewresearch.com/industry-analysis/india-glp-1-receptor-agonist-market-report",
      "description": "GLP-1 Market Growth Rate (CAGR 2025-2030)",
      "percents_found": [
        "34.3%",
        "71.9%",
        "27%",
        "1.0",
        "2.4",
        "44%",
        "20%",
        "39%"
      ],
      "rupees_found": [],
      "excerpt": "India GLP-1 Receptor Agonist Market | Industry Report 2030 Grand View Research Logo Home Industries Consumer Goods Beauty & Personal Care Specialty & Fine Chemicals Food & Beverages Advanced Materials Explore All Industries Companies Basic Materials Consumer Defensive Energy Financial Services Healthcare Industrials Real Estate Technology Utilities Explore All Companies Services Astra (ESG Solutio..."
    },
    {
      "url": "https://m.economictimes.com/industry/healthcare/biotech/pharmaceuticals/a-big-fat-fight-has-just-broken-out-in-india/articleshow/122049705.cms",
      "description": "GLP-1 Anti-Obesity Drug Market Value (March 2025) & Pricing",
      "percents_found": [
        "74.2",
        "0.4%",
        "77%",
        "50%",
        "9.1%",
        "322.0",
        "357.6",
        "3.6%",
        "97%",
        "62%"
      ],
      "rupees_found": [
        "\u20b949,999 ",
        "\u20b9 1749 ",
        "\u20b9 49 "
      ],
      "excerpt": "A big fat fight has just broken out in India - The Economic Times Benchmarks Nifty 25,169.50 -32.85 FEATURED FUNDS \u2605\u2605\u2605\u2605\u2605 UTI Aggressive Hybrid Fund Regular Plan-Growth 5Y Return 20.29 % Invest Now FEATURED FUNDS \u2605\u2605\u2605 \u2605\u2605 HSBC Large Cap Fund Direct-Growth 5Y Return 19.28 % Invest Now Enter search text: Industry English Edition English Edition \u0939\u093f\u0928\u094d\u0926\u0940 \u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0 \u092e\u0930\u093e\u0920\u0940 \u09ac\u09be\u0982\u09b2\u09be \u0c95\u0ca8\u0ccd\u0ca8\u0ca1

In [31]:
# Cell 4: Extract and parse numeric info from treatment-related articles

treatment_data = []

for url, desc in tqdm(sources['treatment_patterns'].items()):
    print(f"\n🔗 {desc}\n{url}")
    try:
        r = requests.get(url, timeout=20)
        text = BeautifulSoup(r.text, "html.parser").get_text(" ", strip=True)
        
        percents = re.findall(r"\b\d{1,2}\.\d%|\b\d{1,2}%|\b\d{1,3}\.\d\b", text)
        rupees = re.findall(r"₹\s?\d+[.,]?\d*\s?(?:crore|lakh|million)?", text, re.I)
        
        treatment_data.append({
            "url": url,
            "description": desc,
            "percents_found": list(set(percents))[:10],
            "rupees_found": list(set(rupees))[:10],
            "excerpt": text[:400] + "..."
        })
    except Exception as e:
        print(f"❌ Error scraping {url}: {e}")

  0%|                                                                                            | 0/5 [00:00<?, ?it/s]

🔗 GLP-1 Market Growth Rate (CAGR 2025-2030)
https://www.grandviewresearch.com/industry-analysis/india-glp-1-receptor-agonist-market-report

 20%|████████████████▊                                                                   | 1/5 [00:02<00:08,  2.21s/it]

🔗 GLP-1 Anti-Obesity Drug Market Value (March 2025) & Pricing
https://m.economictimes.com/industry/healthcare/biotech/pharmaceuticals/a-big-fat-fight-has-just-broken-out-in-india/articleshow/122049705.cms

 40%|█████████████████████████████████▌                                                  | 2/5 [00:04<00:07,  2.34s/it]

🔗 GLP-1 Patient Openness/Barriers (77.3% Openness)
https://www.iosrjournals.org/iosr-jpbs/papers/Vol19-issue6/Ser-2/L1906027179.pdf

 60%|██████████████████████████████████████████████████▍                                 | 3/5 [00:14<00:11,  5.96s/it]

🔗 Bariatric Surgery Cost Range (Lakhs)
https://nobesity.in/weight-loss-surgery-cost-in-india/

 80%|███████████████████████████████████████████████████████████████████▏                | 4/5 [00:18<00:04,  4.89s/it]

🔗 Lifestyle Intervention (Clinical Basis)
https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2024.1382814/full

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:22<00:00,  4.47s/it]

In [32]:
# Cell 5: Show what we found
for item in treatment_data:
    print(f"\n📘 {item['description']}")
    print(f"🔗 {item['url']}")
    print(f"Percentages found: {item['percents_found']}")
    print(f"Currency mentions: {item['rupees_found']}")
    print("Excerpt:", item['excerpt'][:250], "...\n")

📘 GLP-1 Market Growth Rate (CAGR 2025-2030)
🔗 https://www.grandviewresearch.com/industry-analysis/india-glp-1-receptor-agonist-market-report
Percentages found: ['34.3%', '71.9%', '27%', '1.0', '2.4', '44%', '20%', '39%']
Currency mentions: []
Excerpt: India GLP-1 Receptor Agonist Market | Industry Report 2030 Grand View Research Logo Home Industries Consumer Goods Beauty & Personal Care Specialty & Fine Chemicals Food & Beverages Advanced Materials Explore All Industries Companies Basic Materials  ...


📘 GLP-1 Anti-Obesity Drug Market Value (March 2025) & Pricing
🔗 https://m.economictimes.com/industry/healthcare/biotech/pharmaceuticals/a-big-fat-fight-has-just-broken-out-in-india/articleshow/122049705.cms
Percentages found: ['74.2', '0.4%', '77%', '50%', '9.1%', '322.0', '357.6', '3.6%', '97%', '62%']
Currency mentions: ['₹49,999 ', '₹ 1749 ', '₹ 49 ']
Excerpt: A big fat fight has just broken out in India - The Economic Times Benchmarks Nifty 25,169.50 -32.85 FEATURED FUNDS ★★★★★ UTI Aggressive Hybrid Fund Regular Plan-Growth 5Y Return 20.29 % Invest Now FEATURED FUNDS ★★★ ★★ HSBC Large Cap Fund Direct-Grow ...


📘 GLP-1 Patient Openness/Barriers (77.3% Openness)
🔗 https://www.iosrjournals.org/iosr-jpbs/papers/Vol19-issue6/Ser-2/L1906027179.pdf
Percentages found: ['2%', '3.9', '1.0', '3%', '1.3', '12%', '2.5', '3.0', '2.7', '9%']
Currency mentions: []
Excerpt: %PDF-1.7
%����
1 0 obj
< >/Metadata 785 0 R/ViewerPreferences 786 0 R>>
endobj
2 0 obj
< >
endobj
3 0 obj
< >/ExtGState< >/ProcSet[/PDF/Text/ImageB/ImageC/ImageI] >>/MediaBox[ 0 0 595.44 841.68] /Contents 4 0 R/Group< >/Tabs/S/StructParents  ...


📘 Bariatric Surgery Cost Range (Lakhs)
🔗 https://nobesity.in/weight-loss-surgery-cost-in-india/
Percentages found: ['7.5', '2.5']
Currency mentions: ['₹8 lakh', '₹2.25 lakh', '₹2.5 lakh', '₹7.5 lakh', '₹2.75 lakh', '₹1 lakh', '₹6 lakh']
Excerpt: Weight Loss Surgery Cost in Ahmedabad, India | Bariatric Guide About Why NObesity? Our Team Facilities Awards and Recognitions Media Coverage Story of 27 Surgeries in 16 Hours Record Events Weight Loss Treatment Bariatric Surgery Gastric Bypass Surge ...


📘 Lifestyle Intervention (Clinical Basis)
🔗 https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2024.1382814/full
Percentages found: ['50%', '15%', '10.3%', '39.6%', '3.0', '5.9', '62.3', '16.7%', '10.2', '2.6%']
Currency mentions: []
Excerpt: Frontiers | Semaglutide for weight loss: unanswered questions Frontiers in Endocrinology About us About us Who we are Mission and values History Leadership Awards Impact and progress Frontiers' impact Our annual reports Publishing model How we publis ...